:title: Verbose Logging
:ga_code: UA-2062105-4
:user_agent: verbose logging http://verboselogging.com/
:tagline: software development with some really amazing hair
:host: verboselogging.com
:email: darkhelmet@darkhelmetlive.com
:author: Daniel Huckstep
:feedburner: VerboseLogging
:disqus: verboselogging